### ISSUE TITLE
Make links work in call scripts

### ISSUE THREAD

**Issue by sahadeva** [IndivisibleTemplate/BasicTemplate#11]
See http://indivisiblecolusa.com/action/2017/04/02/call-feinstein-vote-no-on-cloture.html 

This is a chapter using the software that has tried to put a link into the call script. For some reason it's not working...

**Comment by sah** [comment]
Example page is gone now, but e.g. http://indivisiblecolusa.com/action/2017/04/02/spread-the-word-share-our-flyer.html seems to have working links. Maybe they figured it out?

**Comment by sahadeva** [comment]
It looks like they removed the contents of `call-script-text` field because links were not working, so you don't see a call script on that page anymore. I reproduced it here: https://sahadeva.github.io/action/2017/02/22/send-raggedy-andy-home-call-your-senator-now.html (this repo is a slightly older version of the styles). 

Note that the markdown in the *Call Script* section of the page doesn't render. E.g. the link markdown `[Link Test](http://indivisibletemplate.com)` doesn't work in the call script but does work in the post content below it.
