### ISSUE TITLE
Representative's info not showing up in footer

### ISSUE THREAD

**Issue by sahadeva** [IndivisibleTemplate/BasicTemplate#16]
See footer here: http://indivisiblecolusa.com/

Correctly showing up: https://github.com/colusa/colusa.github.io/blob/master/_representatives/sen-dianne-feinstein.markdown

Phone numbers not showing up: https://github.com/colusa/colusa.github.io/blob/master/_representatives/congressman-john-garamendi.markdown

**Comment by annakrasner** [comment]
@sahadeva i reproed this bug on my local branch by converting phone-numbers to a Simple and adding one phone number, then re-converting the ENTRY to an object to add the keys as for otehr senators. It seems to be some bug in site-leaf where phone-numbers type is not an object after this. From Colusa's history, it seems something like this happened for them as well.

To fix it, I clicked on the (...) on the phone numbers title field and converted it to an object, then re-added the numbers. That fixed it locally. Mabye try suggesting it to them?

![image](https://cloud.githubusercontent.com/assets/5192273/24699713/c8cf71ae-19a9-11e7-8f19-92ac2a498776.png)

Will look further into it when i have time

**Comment by annakrasner** [comment]
for myself: {% if var.first %}
  // var is not a string
{% else %}
 // var is a string
{% endif %}

**Comment by sahadeva** [comment]
@annakrasner I did suggest to them and it seems to have worked. thank you! Should I forward to Siteleaf folks as a bug?
