### ISSUE TITLE
Support site: Discourse or slack channel or something else?

### ISSUE THREAD

**Issue by sahadeva** [IndivisibleTemplate/BasicTemplate#30]
Recommend a web tool that non-technical people can use to send in support requests for Indivisible Template and get timely support. Ideally would have a knowledge base component to avoid repeat requests. 

This will be particularly important as usage grows. 

A link to this would exist in the documentation and potentially in the site footer.

**Comment by kfitzpatrick** [comment]
Zendesk seems to be where most people I know end up.

**Comment by sahadeva** [comment]
Discourse has been set up here: http://discourse.indivisibletemplate.com/
