### ISSUE TITLE
Email compose code not correct

### ISSUE THREAD

**Issue by sahadeva** [IndivisibleTemplate/BasicTemplate#45]
![unnamed](https://cloud.githubusercontent.com/assets/19377/25114833/7470c10a-23b6-11e7-9c10-ff61ccf13888.jpg)

**Comment by sah** [comment]
The `mailto:` url in `becomeAMember.html` and `footer.html` needs `&body=` instead of `?body=`

**Comment by kfitzpatrick** [comment]
Is this issue still live? It looks like a nice easy one for me to start with.
