### ISSUE TITLE
Markdown Errors? 

### ISSUE THREAD

**Issue by sahadeva** [IndivisibleTemplate/BasicTemplate#47]
This is the output: http://indivisibleoc46.org/action/2017/04/15/win-blue-seats-across-the-country.html

Notice the weird `//` characters.

Here is what the user is Seeing in Siteleaf:

![screen shot 2017-04-17 at 11 04 50 pm](https://cloud.githubusercontent.com/assets/19377/25144173/c7a69a64-2421-11e7-8667-0e333248af36.jpg)

**Comment by kfitzpatrick** [comment]
Those look like they are line returns being stored with some sort of escaping that is being rendered without unescaping by the siteleaf engine. I suspect this text was copy & pasted from a Word document or something.

**Comment by sahadeva** [comment]
Oh, yes, I think this person mentioned that they were copied and pasted from a Google doc. I'll ask them to write somethign from scratch and see if they still have the issue. Thank you @kfitzpatrick 👍

**Comment by sahadeva** [comment]
Confirmed with user that it was pasted from Google Docs. Will close this for now. Good catch @kfitzpatrick !
