### ISSUE TITLE
Subdomain setup for Discourse

### ISSUE THREAD

**Issue by sahadeva** [IndivisibleTemplate/BasicTemplate#50]
I set up Discourse at `http://162.243.65.134/` on Digital Ocean

I'm not sure how to set up my DNS to get that to work for `discourse.indivisibletemplate.com`. I'm using Google domains...

**Comment by kfitzpatrick** [comment]
Just gotta set up a CNAME record on google domains pointing at that IP.

This should point you in the right direction: https://support.google.com/a/answer/86167?hl=en

**Comment by sahadeva** [comment]
OK, 

so for these fields: 

<img width="821" alt="screen shot 2017-04-19 at 5 40 11 pm" src="https://cloud.githubusercontent.com/assets/19377/25208150/8414ea38-2527-11e7-9532-eb80cc91f0c9.png">

I would enter `discourse.indivisibletemplate.com` for the first (1) and `162.243.65.134` for the second (2)?

**Comment by kfitzpatrick** [comment]
Did that work?
