### ISSUE TITLE
Someone to manage discourse.indivisibletemplate.com

### ISSUE THREAD

**Issue by sahadeva** [IndivisibleTemplate/BasicTemplate#52]
Would love some help getting this set up a little over my head.

Installation instructions: https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md

I think we want to set up a https://letsencrypt.org/ cert to get https? I tried to do that by updating the config file on the completed installation but somehow broke the whole thing :(

**Comment by sahadeva** [comment]
Someone with technical skillz wanted

**Comment by kfitzpatrick** [comment]
Specifically what are we missing?

**Comment by sahadeva** [comment]
Ack @kfitzpatrick sorry I missed your comment. Bob is helping out. If you want to join in let me know!

**Comment by cantoni** [comment]
Is the config file that you changed part of digitalocean.com?

**Comment by sahadeva** [comment]
Yes it should be. It's described here: https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md#edit-discourse-configuration

I ran `./discourse-setup` again after connecting to the server and that's what crashed it if I remember correctly.
